sudo: required
services:
   - docker
before_install:
   - docker build -t ashanb/react-test2 -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true ashanb/react-test2 npm test npm test -- --coverage

after_success:
   - docker build -t ashanb/multi-client ./client
   - docker build -t ashanb/multi-nginx ./nginx
   - docker build -t ashanb/multi-server ./server
   - docker build -t ashanb/multi-worker ./worker
   # Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   # Take those images and push them to docker hub
   - docker push ashanb/multi-client
   - docker push ashanb/multi-nginx
   - docker push ashanb/multi-server
   - docker push ashanb/multi-worker

deploy:
   provider: elasticbeanstalk
   region: us-east-1
   app: multi-docker
   env: MultiDocker-env
   bucket_name: elasticbeanstalk-us-east-1-442349120593
   buket_path: docker-multi
   on:
      branch: master 
   access_key_id: $AWS_ACCESS_KEY
      secure: $AWS_ACCESS_KEY
      secure: $AWS_SECRET_KEY
  