sudo: required
services:
   - docker
before_install:
   - docker build -t asbalk/react-test2 -f ./client/Dockerfile.dev ./client

script:
   - docker run asbalk/react-test2 npm test npm test -- --coverage

after_success:
   - docker build -t asbalk/multi-client ./client
   - docker build -t asbalk/multi-nginx ./nginx
   - docker build -t asbalk/multi-server ./server
   - docker build -t asbalk/multi-worker ./worker
   # Take those images and push them to docker hub
   # Log in to the docker CLI